version: '2'
services:
  jenkins:
    image: 'devsouza01/jenkins_with_docker:latest'
#    image: 'jenkins/jenkins:lts'
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

